### PR TITLE
Autoformatting

### PR DESCRIPTION
**Pull request by bolliger32**
No changes to code functionality - just autoformatted a bunch of code with `black`

### CODE REVIEW

**Comment by dpa9694** [comment]
@bolliger32 this all looks good to me!
I had to resolve a couple merge conflicts with the Italy script and `merge.py`, and then re-formatted those with `black`.
Since everything else is just formatting, and since the `pull_request` pipeline fails at the same point as in `master`, I think I'll approve. 
The `push` pipeline fails earlier, with a URL request in the USA script (screenshot), but this seems like it may be a server-side issue since it doesn't occur in the `pull_request` pipeline (I still don't totally understand the difference between the two)

image

**Comment by dpa9694** [comment]
@bolliger32 would it be worth adding `black .` to the `run` script? I worry that every PR updating Python code is going to run into annoying merge conflicts, and those updates will not themselves be formatted

**Comment by bolliger32** [comment]
> @bolliger32 would it be worth adding `black .` to the `run` script?

@dpa9694 good idea but I think not in run, b/c you could be running the run script without wanting to reformat things. I added a formatting checker to the `run_tests.sh` script so we will see the pipeline fail if it doesn't match the formatter (like how we do w/ `pyTC`)

**Comment by dpa9694** [comment]
> 
> 
> > @bolliger32 would it be worth adding `black .` to the `run` script?
> 
> @dpa9694 good idea but I think not in run, b/c you could be running the run script without wanting to reformat things. I added a formatting checker to the `run_tests.sh` script so we will see the pipeline fail if it doesn't match the formatter (like how we do w/ `pyTC`)

Oh nice! didn't see that

**Pull request merged**
