### PR TITLE
Update usa_policy_data_sources.csv

### PR DESCRIPTION
**Pull request by ekrasovich**
updated the policy intensity coding to tease out business closures - per sol & jeanette's request. data is up to date as of today 4/9. @jeanettelt @estherrolf  @bolliger32

### CODE REVIEW

**Comment by kendonB** [comment]
@estherrolf or @dpa9694 can you run the code downstream of this and push to this PR?

**Comment by bolliger32** [comment]
@kendonB do you think we should just merge this upstream step, and then let another PR deal with the downstream effects?

@ekrasovich looks like we hav another merge conflict. Can you do me a favor and call `git pull origin master` while in your branch, figure out what has changed in the master branch's version of the policy data sources csv, resolve the conflict, and then `git push` again? If you are sure the one you have here is the most up-to-date version, you can call `git checkout --ours data/raw/usa/usa_policy_data_sources.csv` after `git pull origin master`, which will tell git to keep all of your version and none of the conflicting version that is currently on master.

**Comment by ekrasovich** [comment]
@bolliger32 i am using the desktop app, so not sure how to do it this way ^. Let me see what i can do. i am also sure that the one i have is the most current version.

**Comment by ekrasovich** [comment]
i think the issue is that i have to download the new csv from gsheets, save it with the same name as the previous file and then add it to git. i think that git doesnt like that im adding a technically new file with the same name as before because i am replacing it rather than deleting. @bolliger32 i am trying to fix this via terminal but still not working. should i just delete the file altogether, push, then save the new one in? not sure whats best. it wont let me do git checkout --ours

**Comment by ekrasovich** [comment]
this should be resolved now in #135 @bolliger32

**Comment by bolliger32** [comment]
Thats interesting. That shouldn't be an issue as git recognizes that it's the same file name...not sure what was going on. Maybe something weird about the desktop app...not sure. Glad it's resolved and thanks!

**Pull request closed without merging**
