### PR TITLE
Irn update

### PR DESCRIPTION
**Pull request by andyhultgren**
Update to Iran data and policies.

Note: @dpa9694 will need to run his post-processing script.

### CODE REVIEW

**Comment by dpa9694** [comment]
@andyhultgren Thanks! Can you specify the type of travel ban for `travel_ban_optional`?

The list in the data_dictionary / template includes `travel_ban_local`, `travel_ban_intl_out`, and `travel_ban_intl_in`. Once the interim field matches one of these, or you make the case that this is a new category of policy that should be added to these lists, I can re-run.

Also, if you can rename the `_optional` part to just `_opt`, that will match the template and the other countries.

**Comment by andyhultgren** [comment]
@dpa9694 Sorry about that, thought I had fixed that already! Fixed now. Thanks for catching!

**Comment by dpa9694** [comment]
@andyhultgren Thank you! Just one more thing, I'm pulling from `data/interim/iran/IRN_interim.csv` and `data/interim/iran/adm0/IRN_interim.csv`, where it looks like the travel columns weren't updated along with the policies file. Could you update those?

**Comment by andyhultgren** [comment]
@dpa9694 files updated with the travel policy columns. sorry about that!

@bolliger32 removed the setwd call (note this was commented out already)

Also Ian, on the policies workflow comment. Time is extremely constrained at the moment. The readme describes the current workflow, which is reproducible. How important is this?

**Comment by dpa9694** [comment]
@andyhultgren @bolliger32 Ok I ran the script to create the `IRN_processed.csv` files. I also added the file `data/raw/iran/IRN_policy_data_sources.csv` using the information in `data/interim/iran/covid_iran_policies.csv`, to match the structure of other countries' data source files.
Maybe we can leave out the implementation of connecting that file with the script for now.
As far as I can tell everything is ready to merge!

**Comment by bolliger32** [comment]
Awesome! Yeah I don't think it's necessary, but I think would be nice to connect those in the scripts when we can. @dpa9694 did you double check that the google sheet is up to date and matches the information in the `covid_iran_policies.csv`? After that, feel free to merge! I'm accepting now

**Comment by dpa9694** [comment]
> 
> 
> Awesome! Yeah I don't think it's necessary, but I think would be nice to connect those in the scripts when we can. @dpa9694 did you double check that the google sheet is up to date and matches the information in the `covid_iran_policies.csv`? After that, feel free to merge! I'm accepting now

Yep it's the same

**Pull request merged**
