### PR TITLE
Final pass before tagging initial version

### PR DESCRIPTION
**Pull request by bolliger32**
Checking:
- errors brought about by JHU website changing are handled gracefully
- all code runs start to finish including stata
- the intermediate data outputs match the data thats in the latest commit
- final figures/tables look the same as whats in the initial submission
- manually corrected some FIPS codes so that we get populations for all US counties

### CODE REVIEW

**Comment by dpa9694** [comment]
@bolliger32 I'm running a script to check the format of different `[country]_processed.csv`'s, and I get the following:
image
Is this a known issue or should it be resolved here?

**Comment by bolliger32** [comment]
> @bolliger32 I'm running a script to check the format of different `[country]_processed.csv`'s, and I get the following:
> image
> Is this a known issue or should it be resolved here?

thanks for catching! It's a known issue (see convo on #covid_github). I just pushed an update to account for `pop_is_imputed`. @sannanphan is fixing the FRA dataset in #32. Can you add this automated check as a new script and a step in `run` ? Have it throw a warning right now, but create an issue to change it to raising an error, which we can enable once #32 is merged and all the datasets match

**Comment by dpa9694** [comment]
Will do!

**Comment by dpa9694** [comment]
@bolliger32 Should "api_keys.json" be appearing here? It's in .gitignore but showing up still. Also, should I commit with all these changes? (all I did was `run`)
image

**Comment by dpa9694** [comment]
Also these new files
image

**Comment by dpa9694** [comment]
Also these new files
image

**Comment by bolliger32** [comment]
> @bolliger32 Should "api_keys.json" be appearing here? It's in .gitignore but showing up still. Also, should I commit with all these changes? (all I did was `run`)
> image

@dpa9694 thanks!

I would not commit api_keys.json. Not sure why it's still appearing but mainly I just want to make sure people don't commit their api keys. So I would not add that. We do want to have an api_keys.json there so users have a template for adding their key. So just don't commit yours :)

I wouldn't add those other files. You can call git diff on them, but I think for most of them, you'll just be adding a new "time downloaded" column onto the same data and/or just changing the whitespace at the end of each line. I did a lot of this checking earlier. Feel free to check some of them if you want, but I checked most of those diffs. 

Don't commit the html file.

The france file is weird. It just showed up for me too. It's something that changed in `scrape_conf_cases_by_region.R` I'll look into that.

Will you check whats different in the adm.csv files?

**Comment by dpa9694** [comment]
@bolliger32 Sounds good. All looks good to me! ready to merge as far as I can tell!

**Pull request merged**
