### PR TITLE
Update usa_policy_data_sources.csv

### PR DESCRIPTION
**Pull request by ekrasovich**
updated error in policy intensity coding caught by @jeanettelt. @dpa9694 notifying you in case you have to re-run the processing step. @bolliger32 also just as an FYI

### CODE REVIEW

**Comment by ekrasovich** [comment]
just pushed again @jeanettelt

**Comment by bolliger32** [comment]
Thanks @ekrasovich ! Looks like there's a merge conflict in this file. Can you resolve and then I'll merge!

**Comment by ekrasovich** [comment]
this has been updated on the gsheet! i had just resacved the gsheet and pushed, but i forgot to fetch before pushing. i am not sure how to resolve the conflict though, @bolliger32 any recommendations?

**Comment by bolliger32** [comment]
@ekrasovich sorry yeah it's not always very straightforward. I just resolved it for the sake of time this time around. But you can click on the "resolve conflicts" button. It'll take you to an editor where you can see what your version looks liek and what the version on master looks like. Conflicts arise when there have been updates to the same lines of a file in the master branch as well as in your branch. This can be helped by frequently calling `git pull origin master` while in your branch locally. But in this case, we just wanted to replace the entire file, so it was clear that the correct path to resolve the merge was to take all of your updates and to drop all of the updates on master. I know that's probably super confusing. Merge conflicts can be challenging for sure.

**Pull request merged**
