### PR TITLE
ignore new fields in italy case data

### PR DESCRIPTION
**Pull request by dpa9694**
Updated the Italy processing script to ignore any fields not specified by the script. 
This is due to an update in the Italy repo (https://github.com/pcm-dpc/COVID-19) with new fields, for a note in Italian and a note in English.

### CODE REVIEW

**Comment by bolliger32** [comment]
@dpa9694 does this PR also contain updated data? If so, I'll hold off until I tag a "initial submission" version after @trinetta has solved #8

**Comment by trinetta** [comment]
I think this is an important update, it currently breaks `codes/data/italy/italy-download-cases-merge-policies.py` (and `run`) because it creates an assertion error when checking if there's a difference in number of columns between the template and the downloaded ITA data, this applies to anyone who runs that python code because the downloading of data happens anyway, I would propose merging this in as soon as possible

**Comment by dpa9694** [comment]
@bolliger32 @trinetta Sorry I started the branch just to ignore new fields so the assert statement would work, but I also updated the way we're doing population weighting, and fixed an issue I hadn't caught, where municipalities (adm3) within a province (adm2) were not accumulating the adm2 pop-weights over time, but only on a single day.

**Comment by dpa9694** [comment]
Also removed date filter (#21 )

**Comment by bolliger32** [comment]
OK! @trinetta @dpa9694 I'm a bit stuck now. I don't want to update data that will change results, but I don't want the code to break if someone runs it. Any chance we can separate these into 2 PRs? I want to merge the new-columns fix and the fix to running the iran data that @trinetta is working on, then tag that revision of the repo, then start merging in all of these code and data updates.

**Comment by dpa9694** [comment]
@bolliger32 the first commit is the only one we need for the "ignore fields" task.
This commit didn't change `adm2/ITA_processed.csv`, and it changed just one number in `adm1/ITA_processed.csv`, the imputed number of recoveries in Campania on 3/18, from 29 to 28 (and this change was due to post-3/18 data being added, changing the imputation).
Since the Italy analysis is on adm2, can we just split off that first commit from the rest?

**Comment by bolliger32** [comment]
@dpa9694 yup can you split that off as a new PR?

**Comment by dpa9694** [comment]
@bolliger32 I reset the latter commits, so this is just dropping those fields now.

**Pull request merged**
