### PR TITLE
update filepath to data

### PR DESCRIPTION
**Pull request by trinetta**
updated filepath to KOR data & updated readme formatting

### CODE REVIEW

**Comment by bolliger32** [comment]
@trinetta since that data is directly downloaded from the pop website, I feel like it actually should be in `data/raw`...what do you think?

**Comment by trinetta** [comment]
I think that makes sense! would you then be able to help move these 2 files from `data/interim/korea/` to `data/raw/korea/`?
`KOR_interim.csv`
`KOR_health.csv`

Currently both are residing in `data/interim/korea/` but would be great if they were moved to the correct folder! Then feel free to delete this branch too! My code on the master branch is currently already pointing to raw, but these 2 files are still in interim (totally my bad, I must have moved it sometime after you had already zipped the DB files)

**Comment by bolliger32** [comment]
ok sounds good!

**Comment by bolliger32** [comment]
Wait @trinetta i'm so sorry! I looked a little further and it seems there are additional manual steps to adjust the downloaded population file. At some point we should probably automate the scraping and processing, but for now I DO think it makes sense to have this in interim. So I just added a bit more detail to the manual instructions and kept things as they are. Does it make sense as is (w/o moving around any files)? I think so but want to double check before I approve and merge.

**Comment by trinetta** [comment]
@bolliger32 yes I think that works! Essentially all I'm doing is merging the population file with the health and population data to create a new file called KOR_interim.csv, so it can definitely swing either way (both as raw or interim). Thanks for taking a second look at this! Go ahead and merge :)

**Pull request merged**
