### PR TITLE
remove USA event_cancel (private or primary postponement)

### PR DESCRIPTION
**Pull request by jeanettelt**

### CODE REVIEW

**Comment by bolliger32** [comment]
@jeanettelt I think this will break b/c downstream files have not been updated.

**Review by bolliger32 — CHANGES_REQUESTED** [review]
Sorry to be picky - Nothing about the actual analysis should change and it looks like all of these changed files are just changes in the "insignificant" figures just due to running on different machines. Could we keep the following diffs, and then revert the others to the current master commit. That *should* pass all the tests. If it doesn't, then we should think about why not:

- README.md
- data/interim/usa/USA_policy_data_sources.csv
- data/raw/usa/USA_policy_data_sources.csv
- data/processed/adm1/USA_processed.csv

**Comment by dpa9694** [comment]
> Sorry to be picky - Nothing about the actual analysis should change and it looks like all of these changed files are just changes in the "insignificant" figures just due to running on different machines. Could we keep the following diffs, and then revert the others to the current master commit. That _should_ pass all the tests. If it doesn't, then we should think about why not:
> 
>     * README.md
> 
>     * data/interim/usa/USA_policy_data_sources.csv
> 
>     * data/raw/usa/USA_policy_data_sources.csv
> 
>     * data/processed/adm1/USA_processed.csv

Yeah that makes sense, I'll revert the other changes.

**Review by bolliger32 — APPROVED** [review]

**Comment by bolliger32** [comment]
Looks good! confirmed this has no effect on the US model results

**Pull request merged**
